//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.UserManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitecture.UserManagement.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد یکبار مصرف وارد شده قبلا استفاده شده است.
        /// </summary>
        internal static string ConsumedOtpError {
            get {
                return ResourceManager.GetString("ConsumedOtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد یکبار مصرف منقضی شده است.
        /// </summary>
        internal static string ExpiredOtpError {
            get {
                return ResourceManager.GetString("ExpiredOtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشست کاربری شما منقضی شده است.
        /// </summary>
        internal static string ExpiredSessionError {
            get {
                return ResourceManager.GetString("ExpiredSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات واردشده با درخواست کد یکبار مصرف مطابقت ندارد.
        /// </summary>
        internal static string InvalidOtpCredentialError {
            get {
                return ResourceManager.GetString("InvalidOtpCredentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد یکبار مصرف واردشده صحیح نیست.
        /// </summary>
        internal static string InvalidOtpError {
            get {
                return ResourceManager.GetString("InvalidOtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        internal static string InvalidPasswordCredentialError {
            get {
                return ResourceManager.GetString("InvalidPasswordCredentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه است.
        /// </summary>
        internal static string InvalidPassworError {
            get {
                return ResourceManager.GetString("InvalidPassworError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل واردشده در سیستم ثبت نشده است.
        /// </summary>
        internal static string MobileNumberNotFoundError {
            get {
                return ResourceManager.GetString("MobileNumberNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر احراز هویت نشده است.
        /// </summary>
        internal static string UnauthorizedError {
            get {
                return ResourceManager.GetString("UnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیر فعال است.
        /// </summary>
        internal static string UserIsLockedOutError {
            get {
                return ResourceManager.GetString("UserIsLockedOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری در دسترس نیست.
        /// </summary>
        internal static string UsernameAlreadyExistsError {
            get {
                return ResourceManager.GetString("UsernameAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر نامعتبر است.
        /// </summary>
        internal static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
    }
}
