//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationEventBus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationEventBus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @result INT;
        ///EXEC @result = sys.sp_getapplock
        ///    @Resource = @Resource,
        ///    @LockMode = &apos;Exclusive&apos;,
        ///    @LockOwner = &apos;Session&apos;,
        ///    @LockTimeout = 0;
        ///SELECT @result;
        ///.
        /// </summary>
        internal static string AcquireSubscriptionLock {
            get {
                return ResourceManager.GetString("AcquireSubscriptionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;WITH [Active] AS
        ///(
        ///    SELECT
        ///        d.[Id],
        ///        e.[Sequence] AS [EventSequence],
        ///        d.[BlocksFollowing],
        ///        d.[NextAttemptAtUtc]
        ///    FROM [cap].[Deliveries] AS d WITH (UPDLOCK, HOLDLOCK, ROWLOCK)
        ///    INNER JOIN [cap].[Events] AS e ON e.[Id] = d.[EventId]
        ///    WHERE d.[SubscriptionName] = @SubscriptionName
        ///      AND d.[Status] IN (@Pending, @Retrying)
        ///),
        ///[Gate] AS
        ///(
        ///    SELECT MIN([EventSequence]) AS [EventSequence]
        ///    FROM [Active]
        ///    WHERE [BlocksFollowing] = 1
        ///),
        ///[Candida [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClaimNextDelivery {
            get {
                return ResourceManager.GetString("ClaimNextDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET XACT_ABORT ON;
        ///BEGIN TRANSACTION;
        ///
        ///DECLARE @lockResult INT;
        ///EXEC @lockResult = sys.sp_getapplock
        ///    @Resource = N&apos;IntegrationEventBus:Schema:cap&apos;,
        ///    @LockMode = &apos;Exclusive&apos;,
        ///    @LockOwner = &apos;Transaction&apos;,
        ///    @LockTimeout = 30000;
        ///
        ///IF @lockResult &lt; 0
        ///    THROW 50000, &apos;Could not acquire the IntegrationEventBus schema lock.&apos;, 1;
        ///
        ///IF SCHEMA_ID(N&apos;cap&apos;) IS NULL
        ///    EXEC(N&apos;CREATE SCHEMA [cap]&apos;);
        ///
        ///IF OBJECT_ID(N&apos;[cap].[Events]&apos;, N&apos;U&apos;) IS NULL
        ///BEGIN
        ///    CREATE TABLE [cap].[Events]
        ///    (
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [cap].[Deliveries]
        ///    ([EventId], [SubscriptionName], [Status], [AttemptCount], [BlocksFollowing],
        ///     [NextAttemptAtUtc], [RetryPolicyName], [RetryPolicyVersion])
        ///VALUES
        ///    (@EventId, @SubscriptionName, @Status, 0, 1, SYSUTCDATETIME(),
        ///     @RetryPolicyName, @RetryPolicyVersion);
        ///.
        /// </summary>
        internal static string InsertDelivery {
            get {
                return ResourceManager.GetString("InsertDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [cap].[Events]
        ///    ([Id], [EventName], [Topic], [PayloadJson], [OccurredAtUtc],
        ///     [CreatedAtUtc], [CorrelationId], [CausationId])
        ///VALUES
        ///    (@Id, @EventName, @Topic, @PayloadJson, @OccurredAtUtc,
        ///     SYSUTCDATETIME(), @CorrelationId, @CausationId);
        ///.
        /// </summary>
        internal static string InsertEvent {
            get {
                return ResourceManager.GetString("InsertEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [cap].[Deliveries]
        ///SET [Status] = @Status,
        ///    [BlocksFollowing] = @BlocksFollowing,
        ///    [NextAttemptAtUtc] = @NextAttemptAtUtc,
        ///    [FirstFailedAtUtc] = COALESCE([FirstFailedAtUtc], @FirstFailedAtUtc),
        ///    [LastError] = @LastError,
        ///    [CompletedAtUtc] = @CompletedAtUtc
        ///WHERE [Id] = @DeliveryId;
        ///.
        /// </summary>
        internal static string MarkFailed {
            get {
                return ResourceManager.GetString("MarkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [cap].[Deliveries]
        ///SET [Status] = @Status,
        ///    [BlocksFollowing] = 0,
        ///    [NextAttemptAtUtc] = NULL,
        ///    [CompletedAtUtc] = @NowUtc,
        ///    [LastError] = NULL
        ///WHERE [Id] = @DeliveryId;
        ///.
        /// </summary>
        internal static string MarkSucceeded {
            get {
                return ResourceManager.GetString("MarkSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [cap].[Deliveries]
        ///SET [AttemptCount] = CASE WHEN [AttemptCount] &gt; 0 THEN [AttemptCount] - 1 ELSE 0 END,
        ///    [NextAttemptAtUtc] = @NowUtc
        ///WHERE [Id] = @DeliveryId;
        ///.
        /// </summary>
        internal static string ReleaseCancelledAttempt {
            get {
                return ResourceManager.GetString("ReleaseCancelledAttempt", resourceCulture);
            }
        }
    }
}
