//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Secrets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitecture.Secrets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0kSgpPoDz/gce1RFNKfIwHjS2DvyQxZDPWiWsI7V+lbPK7SBNzgDCoCCtAZHkNPNzavhPUwkkUYc07R5YPpYwKB7NebT5uiHCpQgGRnA/n2kUvg1vVJCH2FtUtLeyQwMP4T1CXMNBQaDVT5dbtezvcSLwAAFJicpn7IMJFkzrK988yF4mujjhHb6XvqeNYCDxQ2S+IQN7cFFKMh4YbIU50bpMA6g8O0UjAqTNlAxQU=.
        /// </summary>
        internal static string DbMigrationCS {
            get {
                return ResourceManager.GetString("DbMigrationCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Authentication&quot;: {
        ///
        ///    &quot;Default&quot;: {
        ///      &quot;SecurityKey&quot;: &quot;qwertyuiopasdfghjklzxcvbnm123456&quot;,
        ///      &quot;IntrospectionSchema&quot;: null,
        ///      &quot;JwtBearerOptions&quot;: {
        ///        &quot;Authority&quot;: null,
        ///        &quot;Audience&quot;: &quot;www.example.com&quot;,
        ///        &quot;ClaimsIssuer&quot;: &quot;Online JWT Builder&quot;,
        ///        &quot;SaveToken&quot;: true,
        ///        &quot;RequireHttpsMetadata&quot;: true,
        ///        &quot;IncludeErrorDetails&quot;: true
        ///      }
        ///    },
        ///
        ///    &quot;InternalServices&quot;: {
        ///      &quot;SecurityKey&quot;: &quot;qwertyuiopasdfghjklzcdebab654321&quot;,
        ///      &quot;Introspection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DevelopmentAuth {
            get {
                return ResourceManager.GetString("DevelopmentAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;ConnectionStrings&quot;: {
        ///		&quot;ConnectionString&quot;: &quot;Server=.;Database=CleanArchitectureDb;User Id=golshani;Password=Ali_Golshani;TrustServerCertificate=True;&quot;
        ///	}
        ///}.
        /// </summary>
        internal static string DevelopmentCS {
            get {
                return ResourceManager.GetString("DevelopmentCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dg7cK8bsrRT0VAO6GfGKafbY6ou5B622+dN8DVPCzrSrKrDV8+qKNp6Mic8bi/MW6vHJBiUAjzkDgasHyHh7c9/qH6fgkn1LQQVKpLmVodT4KnlHws9YQRkZ0hjpJNxPHZjtPZh3AGdQqASVY5l8QXwDCt2eL8IiwUWStzEVOEmQ4SXpb8BiqTEALWyYk82xavNKTEaNJSUQ/Ibl8MDoqtc9XXtmFWvDeEmqtosZRsPa6k478uTOmeJZPrnpOYwn6rOz/jmmbBv10o1d+AlElbsnKRYq1XiF5RPg+/6qadn1KCxY7ykVLsxfmKXfYnVtsK7oliwTSMjPDmY0NdNzpi3+T/yZ5aIvT835puCvCvVEpJBtYfHe47+987+gZr5n7PHSQi/Y/tBkc9kiRIviZlO0BziPzpVau0eDUlHuFhpJkXswvDI4Ni5MlVbwau+/yU1Jmz7T4x2B+UTP41L3soWJ1VhA4qRBtc8Lk+cuEyfr7gAb4pYNToEKmG1n+ze6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductionAuth {
            get {
                return ResourceManager.GetString("ProductionAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0kSgpPoDz/gce1RFNKfIwHjS2DvyQxZDPWiWsI7V+lbPK7SBNzgDCoCCtAZHkNPNzavhPUwkkUYc07R5YPpYwKB7NebT5uiHCpQgGRnA/n2kUvg1vVJCH2FtUtLeyQwMP4T1CXMNBQaDVT5dbtezvcSLwAAFJicpn7IMJFkzrK988yF4mujjhHb6XvqeNYCDxQ2S+IQN7cFFKMh4YbIU50bpMA6g8O0UjAqTNlAxQU=.
        /// </summary>
        internal static string ProductionCS {
            get {
                return ResourceManager.GetString("ProductionCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dg7cK8bsrRT0VAO6GfGKafbY6ou5B622+dN8DVPCzrSrKrDV8+qKNp6Mic8bi/MW6vHJBiUAjzkDgasHyHh7c9/qH6fgkn1LQQVKpLmVodT4KnlHws9YQRkZ0hjpJNxPHZjtPZh3AGdQqASVY5l8QXwDCt2eL8IiwUWStzEVOEmQ4SXpb8BiqTEALWyYk82xavNKTEaNJSUQ/Ibl8MDoqtc9XXtmFWvDeEmqtosZRsPa6k478uTOmeJZPrnpOYwn6rOz/jmmbBv10o1d+AlElbsnKRYq1XiF5RPg+/6qadn1KCxY7ykVLsxfmKXfYnVtsK7oliwTSMjPDmY0NdNzpi3+T/yZ5aIvT835puCvCvVEpJBtYfHe47+987+gZr5n7PHSQi/Y/tBkc9kiRIviZlO0BziPzpVau0eDUlHuFhpJkXswvDI4Ni5MlVbwau+/yU1Jmz7T4x2B+UTP41L3soWJ1VhA4qRBtc8Lk+cuEyfr7gAb4pYNToEKmG1n+ze6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StagingAuth {
            get {
                return ResourceManager.GetString("StagingAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0kSgpPoDz/gce1RFNKfIwHjS2DvyQxZDPWiWsI7V+lbPK7SBNzgDCoCCtAZHkNPNzavhPUwkkUYc07R5YPpYwKB7NebT5uiHCpQgGRnA/n2kUvg1vVJCH2FtUtLeyQwMP4T1CXMNBQaDVT5dbtezvcSLwAAFJicpn7IMJFkzrK988yF4mujjhHb6XvqeNYCDxQ2S+IQN7cFFKMh4YbIU50bpMA6g8O0UjAqTNlAxQU=.
        /// </summary>
        internal static string StagingCS {
            get {
                return ResourceManager.GetString("StagingCS", resourceCulture);
            }
        }
    }
}
