<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="DotNetCore.CAP.Dashboard" />
		<PackageReference Include="DotNetCore.CAP.SqlServer" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Framework.Messaging\Framework.Messaging.csproj" />
	</ItemGroup>

</Project>
