<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Configuration\CleanArchitecture.ServicesConfigurations\CleanArchitecture.ServicesConfigurations.csproj" />
		<ProjectReference Include="..\..\Framework\IntegrationEventBus\IntegrationEventBus.csproj" />
	</ItemGroup>

</Project>
