// <auto-generated />
using System;
using System.Collections.Generic;
using CleanArchitecture.Ordering.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Ordering.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260420160034_Ordering_Initial")]
    partial class Ordering_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.Ordering.Domain.Orders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<Guid?>("InsertCommandCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("UpdateCommandCorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Commodity", "CleanArchitecture.Ordering.Domain.Orders.Order.Commodity#Commodity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CommodityId")
                                .HasColumnType("int")
                                .HasColumnName("CommodityId");

                            b1.Property<string>("CommodityName")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("CommodityName");
                        });

                    b.HasKey("OrderId");

                    b.ToTable("Orders", "ordering");
                });
#pragma warning restore 612, 618
        }
    }
}
