//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Secrets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitecture.Secrets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0kSgpPoDz/gce1RFNKfIwHjS2DvyQxZDPWiWsI7V+lbPK7SBNzgDCoCCtAZHkNPNzavhPUwkkUYc07R5YPpYwKB7NebT5uiHCpQgGRnA/n2kUvg1vVJCH2FtUtLeyQwMP4T1CXMNBQaDVT5dbtezvcSLwAAFJicpn7IMJFkzrK988yF4mujjhHb6XvqeNYCDxQ2S+IQN7cFFKMh4YbIU50bpMA6g8O0UjAqTNlAxQU=.
        /// </summary>
        internal static string DbMigration {
            get {
                return ResourceManager.GetString("DbMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ConnectionStrings&quot;: {
        ///    &quot;ConnectionString&quot;: &quot;Server=.;Database=CleanArchitectureDb;User Id=golshani;Password=Ali_Golshani;TrustServerCertificate=True;&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0kSgpPoDz/gce1RFNKfIwHjS2DvyQxZDPWiWsI7V+lbPK7SBNzgDCoCCtAZHkNPNzavhPUwkkUYc07R5YPpYwKB7NebT5uiHCpQgGRnA/n2kUvg1vVJCH2FtUtLeyQwMP4T1CXMNBQaDVT5dbtezvcSLwAAFJicpn7IMJFkzrK988yF4mujjhHb6XvqeNYCDxQ2S+IQN7cFFKMh4YbIU50bpMA6g8O0UjAqTNlAxQU=.
        /// </summary>
        internal static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V0kSgpPoDz/gce1RFNKfIwHjS2DvyQxZDPWiWsI7V+lbPK7SBNzgDCoCCtAZHkNPNzavhPUwkkUYc07R5YPpYwKB7NebT5uiHCpQgGRnA/n2kUvg1vVJCH2FtUtLeyQwMP4T1CXMNBQaDVT5dbtezvcSLwAAFJicpn7IMJFkzrK988yF4mujjhHb6XvqeNYCDxQ2S+IQN7cFFKMh4YbIU50bpMA6g8O0UjAqTNlAxQU=.
        /// </summary>
        internal static string Staging {
            get {
                return ResourceManager.GetString("Staging", resourceCulture);
            }
        }
    }
}
